name:                Advent-of-Code
version:             0.1.0.0
github:              "thomasrules2000/Advent-of-Code-2021"
license:             BSD3
author:              "Thomas Stacey"
maintainer:          "Thomas.Stacey@warwick.ac.uk"
copyright:           "2021 Thomas Stacey"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thomasrules2000/Advent-of-Code-2021#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- vector
- matrix
- heap
- extra
- unordered-containers
- mtl
- clock
- formatting

library:
  source-dirs: src
  default-extensions:
    - ApplicativeDo
    - TupleSections
    - NumericUnderscores
    - TypeSynonymInstances
    - FlexibleInstances
    - ScopedTypeVariables
    - DeriveGeneric
    - DeriveAnyClass
    - LambdaCase 
    - DeriveFunctor
    - DeriveFoldable
    - RecordWildCards

executables:
  AOC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -with-rtsopts=-qa
    - -with-rtsopts=-C0
    - -funfolding-use-threshold=16
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    - -O2
    dependencies:
    - Advent-of-Code
